### ISSUE TITLE
Error in visualization of object aggregated samples 

### ISSUE THREAD

**Issue by Annopaolo** [astarte-platform/astartectl#137]
I am running `astartectl 1.0.0-beta.2` with an `astarte 1.0.0` cluster.
When viewing samples from a device on an object aggregated interface with `astartectl appengine devices get-samples`, only a single mapping gets printed, instead of all of them. 
Moreover, if that  mapping's value is missing in other samples to be shown, a null pointer error happens:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x8f1f52]

goroutine 1 [running]:
github.com/jedib0t/go-pretty/table.isNumber(0x0, 0x0, 0x182fd5c)
	/home/runner/go/pkg/mod/github.com/jedib0t/go-pretty@v4.3.0+incompatible/table/util.go:20 +0x42
github.com/jedib0t/go-pretty/table.(*Table).analyzeAndStringify(0xc0001b6000, 0xc0003a2280, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0xc00053b270, 0x4e7728, ...)
	/home/runner/go/pkg/mod/github.com/jedib0t/go-pretty@v4.3.0+incompatible/table/table.go:309 +0x616
github.com/jedib0t/go-pretty/table.(*Table).initForRenderRowsStringify(0xc0001b6000, 0xc0004f4c00, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc0003ac5b0, 0xc000314158, ...)
	/home/runner/go/pkg/mod/github.com/jedib0t/go-pretty@v4.3.0+incompatible/table/table.go:624 +0xf6
github.com/jedib0t/go-pretty/table.(*Table).initForRenderRows(0xc0001b6000)
	/home/runner/go/pkg/mod/github.com/jedib0t/go-pretty@v4.3.0+incompatible/table/table.go:596 +0xbb
github.com/jedib0t/go-pretty/table.(*Table).initForRender(0xc0001b6000)
	/home/runner/go/pkg/mod/github.com/jedib0t/go-pretty@v4.3.0+incompatible/table/table.go:520 +0xa7
github.com/jedib0t/go-pretty/table.(*Table).Render(0xc0001b6000, 0x7f1d08752e98, 0x0)
	/home/runner/go/pkg/mod/github.com/jedib0t/go-pretty@v4.3.0+incompatible/table/render.go:22 +0x40
github.com/astarte-platform/astartectl/cmd/appengine.renderOutput(0x1ad79a0, 0xc0001b6000, 0x1599780, 0xc0003a2320, 0x183341b, 0x7)
	/home/runner/work/astartectl/astartectl/cmd/appengine/device.go:1038 +0x1a5
github.com/astarte-platform/astartectl/cmd/appengine.devicesGetSamplesF(0x265a0c0, 0xc000214d80, 0x3, 0x9, 0x0, 0x0)
	/home/runner/work/astartectl/astartectl/cmd/appengine/device.go:780 +0x1a1a
github.com/spf13/cobra.(*Command).execute(0x265a0c0, 0xc000214cf0, 0x9, 0x9, 0x265a0c0, 0xc000214cf0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2658680, 0x44276a, 0x25f4cc0, 0xc000074778)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/astarte-platform/astartectl/cmd.Execute()
	/home/runner/work/astartectl/astartectl/cmd/root.go:52 +0x31
main.main()
	/home/runner/work/astartectl/astartectl/main.go:20 +0x20
```
This relates to [#598](https://github.com/astarte-platform/astarte/pull/598) (and possibly  [#574](https://github.com/astarte-platform/astarte/pull/574)) on the astarte repo.

**Comment by Annopaolo** [comment]
Closed by #196.
